[package]
name = "rustcat"
version = "0.1.0"
authors = ["Tomer Schwartz <tomeron12@gmail.com>"]

[dependencies]
ctrlc = { version = "3.0", features = ["termination"] }
futures = "0.1"
tokio = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
